# Generated by Django 5.2 on 2026-02-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
