# Generated by Django 5.2 on 2025-10-29 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.delivery'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couriers.riderprofile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='couriers.riderprofile'),
        ),
    ]
